name: First_workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu_latest
    steps:
      - name: print Greeting
        run: echo "hello-world!!"
      - name: print GoodBye
        run: echo "Good-Bye!!"
      
